INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '1');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '2');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '3');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '4');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '5');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '6');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '7');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '8');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '9');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '10');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '11');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '12');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '13');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '14');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '15');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '16');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '17');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '18');
INSERT INTO `datvetau`.`lotrinh_giotauchay` (`LoTrinh_id`, `gioTauChays_id`) VALUES ('1', '19');


INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('1');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('2');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('3');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('4');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('5');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('6');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('7');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('8');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('9');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('10');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('11');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('12');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('13');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('14');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('15');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('16');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('17');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('18');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('19');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('20');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('21');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('22');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('23');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('24');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('25');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('26');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('27');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('28');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('29');
INSERT INTO `datvetau`.`lotrinh` (`id`) VALUES ('30');

INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('2', 'SE3');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('3', 'SE5');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('4', 'SE7');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('5', 'SE9');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('6', 'SE11');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('7', 'SE21');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('8', 'SE27');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('9', 'SE25');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('10', 'SQN1');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('11', 'SNT1');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('12', 'SNT3');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('13', 'SPT1');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('14', 'SPT3');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('15', 'NH1');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('16', 'SE2');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('17', 'SE4');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('18', 'SE6');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('19', 'SE8');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('20', 'SE10');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('21', 'SE12');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('22', 'SE22');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('23', 'SE28');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('24', 'SE26');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('25', 'SQN2');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('26', 'SNT2');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('27', 'SNT4');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('28', 'SPT2');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('29', 'SPT4');
INSERT INTO `datvetau`.`tau` (`id`, `tenTau`) VALUES ('30', 'NH2');

INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`, `khoangCach`) VALUES ('1', 'Hà Nội', 'Hà Nội','0');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('2', 'Giáp Bát', 'Giáp Bát','5.18');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('3', 'Phủ Lý', 'Phủ Lý','55.54');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('4', 'Nam Định', 'Nam Định','86.76');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('5', 'Ninh Bình', 'Ninh Bình','114.62');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('6', 'Bỉm Sơn', 'Bỉm Sơn','141.5');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('7', 'Thanh Hóa', 'Thanh Hóa','17523');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('8', 'Minh Khôi', 'Minh Khôi','196.9');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('9', 'Chợ Sy', 'Chợ Sy','279');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('10', 'Vinh', 'Vinh','319.02');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('11', 'Yên Trung', 'Yên Trung','340.13');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('12', 'Hương Phố', 'Hương Phố','386.18');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('13', 'Đồng Lệ', 'Đồng Lệ','436.33');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('14', 'Minh Lễ', 'Minh Lễ','481.81');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('15', 'Đồng Hới', 'Đồng Hới','521.8');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('16', 'Mỹ Đức', 'Mỹ Đức','550.89');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('17', 'Đông Hà', 'Đông Hà','622.181');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('18', 'Huế', 'Huế','688.32');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('19', 'Lăng Cô', 'Lăng Cô','755.41');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('20', 'Đà Nẵng', 'Đà Nẵng','791.4');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('21', 'Trà Kiệu', 'Trà Kiệu','824.77');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('22', 'Phú Cảng', 'Phú Cảng','841.74');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('23', 'Tam Kỳ', 'Tam Kỳ','864.67');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('24', 'Núi Thành', 'Núi Thành','890.42');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('25', 'Quảng Ngãi', 'Quảng Ngãi','927.93');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('26', 'Đức Phổ', 'Đức Phổ','967.68');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('27', 'Bổng Sơn', 'Bổng Sơn','1017.1');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('28', 'Quy Nhơn', 'Quy Nhơn','1095.54');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('29', 'Diêu Trì', 'Diêu Trì','1095.54');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('30', 'La Hai', 'La Hai','1154.37');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('31', 'Tuy Hòa', 'Tuy Hòa','1197.52');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('32', 'Phú Hiệp', 'Phú Hiệp','	1210.83');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('33', 'Giã', 'Giã','1254.05');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('34', 'Ninh Hòa', 'Ninh Hòa','1280.56');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('35', 'Nha Trang', 'Nha Trang','1314.93');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('36', 'Ngã Ba', 'Ngã Ba','1363.78');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('37', 'Tháp Chàm', 'Tháp Chàm','1407.63');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('38', 'Sông Mao', 'Sông Mao','1484.49');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('39', 'Phan Thiết', 'Phan Thiết','1551.15');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('40', 'Bình Thuận', 'Bình Thuận','1551.15');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('41', 'Suối Kiết', 'Suối Kiết','1603.1');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('42', 'Long Khánh', 'Long Khánh','1649.36');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('43', 'Biên Hòa', 'Biên Hòa','1697.48');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('44', 'Dĩ An', 'Dĩ An','1706.71');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('45', 'Sóng Thần', 'Sóng Thần','1710.56');
INSERT INTO `datvetau`.`nhaga` (`id`, `diaChi`, `tenNhaGa`,`khoangCach`) VALUES ('46', 'Sài Gòn', 'Sài Gòn','1726.2');



